# Python image
FROM python:3.12.4

# Working directory
WORKDIR /app

# Copy source code
COPY . /app

# Copy ENV variables
COPY .env .env

# Install python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Make port available
EXPOSE 8080

# Define app env variable
ENV FLASK_APP=producer.py

# Run app
CMD [ "flask", "run", "--host=0.0.0.0", "--port=8080"]

